-- db/seeds/dogs.sql

DROP TABLE IF EXISTS dogs;

CREATE TABLE dogs (
  id SERIAL PRIMARY KEY UNIQUE NOT NULL,
  name VARCHAR (256) UNIQUE NOT NULL,
  owner VARCHAR (256),
  insta VARCHAR (256),
  breed VARCHAR (256),
  pic VARCHAR (256),
  num_votes integer,
  num_championships integer,
  num_finalfours integer,
  num_eliteeights integer,
  num_sweetsixteens integer
);

INSERT INTO dogs (id, name, owner, insta, breed, pic, num_votes, num_championships, num_finalfours, num_eliteeights, num_sweetsixteens) VALUES
  (
    1,
    'Minnie',
    'leah f',
    'minniepibble',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/minnie.png',
    0,
    0,
    0,
    0,
    0
  ),
  (
    2,
    'Hank the Tank',
    'alex j',
    'the_frenchie_hank',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/hankthetank.jpg',
    0,
    0,
    0,
    0,
    0
  ),
  (
    3,
    'Callie',
    'ariel w',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/callie.jpg',
    0,
    0,
    0,
    0,
    0
  ),
  (
    4,
    'Zeke',
    'zach m',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/zeke.jpg',
    0,
    0,
    0,
    0,
    0
  ),
  (
    5,
    'Riley',
    'zach m',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/riley.jpg',
    0,
    0,
    0,
    0,
    0
  ),
  (
    6,
    'Jasper',
    'meredith l',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/jasper.png',
    0,
    0,
    0,
    0,
    0
  ),
  (
    7,
    'June Bug',
    'matthew b',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/junebug.jpg',
    0,
    0,
    0,
    0,
    0
  ),
  (
    8,
    'Coco',
    'marissa m',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/coco.png',
    0,
    0,
    0,
    0,
    0
  ),
  (
    9,
    'Samson',
    'michael b',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/samson.JPG',
    0,
    0,
    0,
    0,
    0
  ),
  (
    10,
    'Lola Jane',
    'tyler d',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/lolajane.png',
    0,
    0,
    0,
    0,
    0
  ),
  (
    11,
    'Una',
    'clay k',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/una.png',
    0,
    0,
    0,
    0,
    0
  ),
  (
    12,
    'Maximus',
    'april g',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/maximus.png',
    0,
    0,
    0,
    0,
    0
  ),
  (
    13,
    'Gordy',
    'deborah s',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/gordy.png',
    0,
    0,
    0,
    0,
    0
  ),
  (
    14,
    'Riggins',
    'sara h',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/riggins.jpg',
    0,
    0,
    0,
    0,
    0
  ),
  (
    15,
    'Leo',
    'breanna r',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/leo.png',
    0,
    0,
    0,
    0,
    0
  ),
  (
    16,
    'Rudy',
    'riley e',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/rudy.png',
    0,
    0,
    0,
    0,
    0
  ),
  (
    17,
    'Zoe',
    'steve k',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/zoe.jpg',
    0,
    0,
    0,
    0,
    0
  ),
  (
    18,
    'Amma',
    'brenna t',
    'instagr.amma',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/amma.jpg',
    0,
    0,
    0,
    0,
    0
  ),
  (
    19,
    'Thor',
    'amarto r',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/thor.jpg',
    0,
    0,
    0,
    0,
    0
  ),
  (
    20,
    'Mel',
    'ashley s',
    '',
    '',
    'https://github.com/emilyengle/pups-of-seatgeek/raw/master/img/mel.jpg',
    0,
    0,
    0,
    0,
    0
  );
